version: "3.8"

services:
 app:
  build:
   context: ./
   dockerfile: ./docs/docker/application/Dockerfile
  ports:
   - ${HTTP_GATEWAY_PORT}:${HTTP_GATEWAY_PORT}
   - ${GRPC_PORT}:${GRPC_PORT}
  depends_on:
   - database
 
 database:
  build:
   context: ./docs/docker/database
   dockerfile: ./Dockerfile
  environment:
   POSTGRES_DB: ${PG_DB_NAME}
   POSTGRES_USER: ${PG_USER}
   POSTGRES_PASSWORD: ${PG_PASSWORD}
  ports:
  - ${PG_PORT}:5432
